baseURL: https://thebeluga.pro
languageCode: en-GB
title: Beluga Gaming
theme: go
pluralizeListTitles: false
copyright: This work is dual-licensed under MIT & GPL v3
paginate: 2
summaryLength: 13
author:
  name: Alex
  email: aw@atrispina.com
taxonomies:
  tag: tags
params:
  description: Socially aware starter kit for Hugo
  publisher: Alex
  publisherLogo: assets/img/logo.png
  publisherLogoWidth: 220
  publisherLogoHeight: 220
  twitter: AlexWelcing
  email: aw@atrispina.com
