baseURL: https://thebeluga.pro
languageCode: en-GB
title: Worst Coach seeking Best Team
theme: go
pluralizeListTitles: false
copyright: This work is dual-licensed under MIT & GPL v3
paginate: 2
summaryLength: 13
author:
  name: Alex Welcing
  email: aw@atrispina.com
taxonomies:
  tag: tags
params:
  description: Socially aware starter kit for Hugo
  publisher: Alex
  publisherLogo: assets/img/logo.png
  publisherLogoWidth: 220
  publisherLogoHeight: 220
  twitter: Alex
  facebook: Alex
  email: hello@indiego.org.uk
  googleplus: NA
  fbapp_id: NA
  tel: "+NA"
